In [55]:
from keras.preprocessing.image import ImageDataGenerator

In [56]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Dropout, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator

# 建立模型
model = Sequential()
model.add(Conv2D(32, 3, activation='relu', input_shape=(128,128,3)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4, activation='sigmoid'))

# 編譯
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


train_data_dir = 'C:/Users/USER/Desktop/train'
validation_data_dir = 'C:/Users/USER/Desktop/test'
#Keras的processing模塊中提供了一個能夠實時進行數據增強的圖像生成類ImagGenerator
train_datagen = ImageDataGenerator(
        #0~255調成0~1
        rescale=1. / 255,
        #剪切變換的程度
        shear_range=0.2,
        #進行隨機放大
        zoom_range=0.2,
        #隨機對圖像進行水平翻轉 
        horizontal_flip=True)

val_datagen = ImageDataGenerator(rescale=1. / 255)


#從文件夾中獲取圖像數據
train_generator = train_datagen.flow_from_directory(
        train_data_dir, #訓練資料位置
        target_size=(128, 128), # 圖片被resize成 128*128
        batch_size=16,
        class_mode='sparse')

validation_generator = val_datagen.flow_from_directory(
        validation_data_dir, #驗證資料位置
        target_size=(128, 128), # 圖片被resize成 128*128
        batch_size=16,
        class_mode='sparse')

#訓練模型
model.fit_generator(train_generator,
                    steps_per_epoch=62,
                    epochs=5,
                    validation_data=validation_generator,
                    validation_steps=8)


# 保存整個模型
model.save('C:/Users/USER/Desktop/model.hdf5')

# 保存模型的權重
model.save_weights('C:/Users/USER/Desktop/model_weights.h5')

# 保存模型的結構
json_string = model.to_json()
open('model_to_json.json','w').write(json_string)
yaml_string = model.to_yaml()
open('model_to_yaml.yaml','w').write(json_string)


Found 310 images belonging to 4 classes.
Found 40 images belonging to 4 classes.
Epoch 1/5
62/62 [==============================] - 174s 3s/step - loss: 1.0124 - acc: 0.5524 - val_loss: 0.9295 - val_acc: 0.7500
Epoch 2/5
62/62 [==============================] - 186s 3s/step - loss: 0.3824 - acc: 0.8841 - val_loss: 0.0624 - val_acc: 1.0000
Epoch 3/5
62/62 [==============================] - 178s 3s/step - loss: 0.2838 - acc: 0.9332 - val_loss: 0.3382 - val_acc: 0.7308
Epoch 4/5
62/62 [==============================] - 173s 3s/step - loss: 0.1806 - acc: 0.9523 - val_loss: 0.0011 - val_acc: 1.0000
Epoch 5/5
62/62 [==============================] - 173s 3s/step - loss: 0.1442 - acc: 0.9641 - val_loss: 0.0180 - val_acc: 1.0000


3685

In [60]:
from keras.models import load_model
import numpy as np
from keras.preprocessing import image
from keras.preprocessing.image import load_img

# 加載權重
model = load_model('C:/Users/USER/Desktop/model.hdf5')

# 加載圖形
img = load_img('C:/Users/USER/Desktop/IMG_3341.jpg',target_size=(128, 128))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)

predictions = model.predict(img)
print (predictions)


[[3.2464850e-01 1.3758302e-02 8.3446503e-07 5.9604645e-08]]


In [65]:
from keras.models import load_model
import numpy as np
from keras.preprocessing import image
from keras.preprocessing.image import load_img

# 加載權重
model = load_model('model.hdf5')

# 加載圖形
img = load_img('C:/Users/USER/Desktop/0.jpg',target_size=(128, 128))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)

predictions = model.predict(img)
print (predictions)

[[9.5512503e-01 2.4529287e-01 2.8073788e-05 3.1799078e-05]]


In [62]:
from keras.models import load_model
import numpy as np
from keras.preprocessing import image
from keras.preprocessing.image import load_img

# 加載權重
model = load_model('C:/Users/USER/Desktop/model.hdf5')

# 加載圖形
img = load_img('C:/Users/USER/Desktop/IMG_3187.jpg',target_size=(128, 128))
img = image.img_to_array(img) / 255.0
img = np.expand_dims(img, axis=0)

predictions = model.predict(img)
print (predictions)

[[0.0000000e+00 3.3915043e-05 9.9989277e-01 0.0000000e+00]]
